# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  # a1549 cron
  - name: a1621-yta-bacth
    image:
      repository: dtr.rec/a1621/yta
      tag: v1.2.4
      imagePullPolicy: Always
    # optional env vars
    env:
    - name: DB_HOST
      value: "alm-dev-ecommerce-pgeidu0.cre03gm6osgl.eu-west-1.rds.amazonaws.com"
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: "ytbdu00"
    - name: DB_USER
      value: "ecomdu00"
    - name: DB_PASS
      value: "ecom00#01"
    - name: LOG4J_LEVEL
      value: "INFO"
    schedule: "*/15 * * * *"
    args: ["fsproTarifTaskletJob","deleteAllAtStart=true","numeroPartie=1","numeroPartieTotale=4"]
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: Never
